"""meetings table, users.awaiting_profile

Revision ID: 3ef4427e7905
Revises: 9fec074ee331
Create Date: 2026-06-07 08:05:53.738168

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '3ef4427e7905'
down_revision: str | None = '9fec074ee331'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('user1_id', sa.Integer(), nullable=False),
    sa.Column('user2_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'declined', 'postpone_pending', 'postponed', 'cancelled', 'completed', 'no_response', name='meetingstatus', native_enum=False), nullable=False),
    sa.Column('midweek_status_u1', sa.String(length=32), nullable=True),
    sa.Column('midweek_status_u2', sa.String(length=32), nullable=True),
    sa.Column('rating_u1', sa.Integer(), nullable=True),
    sa.Column('rating_u2', sa.Integer(), nullable=True),
    sa.Column('postponed_from_id', sa.Integer(), nullable=True),
    sa.Column('cancelled_by', sa.String(length=16), nullable=True),
    sa.Column('notified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['postponed_from_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['user1_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user2_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meetings_user1_id'), ['user1_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meetings_user2_id'), ['user2_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meetings_week_start'), ['week_start'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('awaiting_profile', sa.Boolean(), nullable=False, server_default=sa.false())
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('awaiting_profile')

    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meetings_week_start'))
        batch_op.drop_index(batch_op.f('ix_meetings_user2_id'))
        batch_op.drop_index(batch_op.f('ix_meetings_user1_id'))

    op.drop_table('meetings')
    # ### end Alembic commands ###
