"""complaints table

Revision ID: 7ef2c14bfa7f
Revises: e84f699bcd06
Create Date: 2026-06-07 19:29:05.520037

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '7ef2c14bfa7f'
down_revision: str | None = 'e84f699bcd06'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('accused_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('open', 'resolved', name='complaintstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['accused_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_complaints_accused_id'), ['accused_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaints_meeting_id'), ['meeting_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_complaints_meeting_id'))
        batch_op.drop_index(batch_op.f('ix_complaints_accused_id'))

    op.drop_table('complaints')
    # ### end Alembic commands ###
