"""users table

Revision ID: 9fec074ee331
Revises: 
Create Date: 2026-06-07 07:50:10.492912

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '9fec074ee331'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mm_user_id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('profile', sa.Text(), nullable=True),
    sa.Column('state', sa.Enum('active', 'paused', 'paused_by_admin', 'paused_by_complaint', name='userstate', native_enum=False), nullable=False),
    sa.Column('unmatched_streak', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_mm_user_id'), ['mm_user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_mm_user_id'))

    op.drop_table('users')
    # ### end Alembic commands ###
