"""meetings declined_by_id

Revision ID: d2528dbe7f65
Revises: f378ec17b379
Create Date: 2026-06-08 16:07:31.142769

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'd2528dbe7f65'
down_revision: str | None = 'f378ec17b379'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('declined_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_meetings_declined_by_id_users', 'users', ['declined_by_id'], ['id']
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_meetings_declined_by_id_users', type_='foreignkey')
        batch_op.drop_column('declined_by_id')

    # ### end Alembic commands ###
