"""meetings midweek_sent_at, survey_sent_at

Revision ID: e84f699bcd06
Revises: 3ef4427e7905
Create Date: 2026-06-07 19:00:25.956631

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'e84f699bcd06'
down_revision: str | None = '3ef4427e7905'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('midweek_sent_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('survey_sent_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.drop_column('survey_sent_at')
        batch_op.drop_column('midweek_sent_at')

    # ### end Alembic commands ###
