"""meetings postpone_by_id

Revision ID: f378ec17b379
Revises: 7ef2c14bfa7f
Create Date: 2026-06-08 15:40:29.242772

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'f378ec17b379'
down_revision: str | None = '7ef2c14bfa7f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('postpone_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_meetings_postpone_by_id_users', 'users', ['postpone_by_id'], ['id']
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_meetings_postpone_by_id_users', type_='foreignkey')
        batch_op.drop_column('postpone_by_id')

    # ### end Alembic commands ###
